### ISSUE TITLE
Camera does not support width and height

### ISSUE THREAD

**Issue by michaeldavie** [michaeldavie/hass_environment_canada#1]
> 2021-09-06 08:56:05 WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.ottawa_rain does not support requesting width and height, please open an issue with the integration author

@bdraco I see that you did some work on this, and I'm not sure how to fix my integration. It returns either a static PNG or animated GIF, and the library accepts a width and height when the object is instantiated but not on a per-request basis. Any suggestions you could provide would be appreciated. Thanks!

**Comment by gwww** [comment]
Anything in this PR useful? https://github.com/roleoroleo/yi-hack_ha_integration/issues/45

**Comment by gwww** [comment]
Turn out to be simple to fix. Change signature to:

`async def async_camera_image(self, width: int | None = None, height: int | None = None) -> bytes | None:`

Add this to top of `camera.py`: `from __future__ import annotations`
